zavrsni/quiz/urls.py
from django.urls import path, re_path
from django.views.static import serve as static_serve

from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('create_quiz/', views.create_quiz, name='create_quiz'),
    path('create_quiz/one_choice/', views.create_one_choice, name='create_one_choice'),
    path('create_quiz/anonymous/', views.create_anonymous, name='create_anonymous'),
    path('new_quiz/add_one_choice/', views.add_one_choice, name='add_one_choice'),
    path('new_quiz/add_anonymous/', views.add_anonymous, name='add_anonymous'),
    path('user_quizzes/', views.user_quizzes, name='user_quizzes'),
    path('quiz_details/<int:quiz_id>/', views.quiz_details, name='quiz_details'),
    path('start_screen/<int:quiz_id>/', views.start_screen, name='start_screen'),
    path('send_message/', views.send_message, name='send_message'),
    path('change_screen/<str:code_for_enter>/', views.change_screen, name='change_screen'),
    path('ajax/players_list/<int:quiz_id>/', views.ajax_players_list, name='ajax_players_list'),
    path('start_quiz/<int:quiz_code>/<int:question_number>/', views.start_quiz, name='start_quiz'),
    path('start_quiz_answer/<int:quiz_code>/<int:question_number>/', views.start_quiz_answer, name='start_quiz_answer'),
    path('ajax/quiz_question/<str:quiz_code>/<int:question_number>/', views.ajax_quiz_question, name='ajax_quiz_question'),
    path('finished_quizzes/', views.finished_quizzes, name='finished_quizzes'),
    path('quiz_results/<int:quiz_id>/', views.quiz_results, name='quiz_results'),
    path('export_results/<int:quiz_id>/', views.export_results, name='export_results'),
    # Urls for quiz players 
    path('join_quiz/<int:quiz_id>/', views.join_quiz, name='join_quiz'),
    path('loading_screen/<int:quiz_id>/', views.loading_screen, name='loading_screen'),
    path('one_choice_question/<int:quiz_id>/', views.one_choice_question, name='one_choice_question'),
    path('anonymous_question/<int:quiz_id>/', views.anonymous_question, name='anonymous_question'),
    path('current_results/<int:quiz_id>/', views.current_results, name='current_results'),

    re_path(r'^firebase-messaging-sw.js/?$', static_serve, {'document_root': 'quiz/static/quiz', 'path': 'firebase-messaging-sw.js'}),

]

zavrsni/zavrsni/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
]

zavrsni/quiz/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Option(models.Model):
    text = models.CharField(max_length=100)
    is_correct = models.BooleanField(default=False)
    
    def __str__(self):
        return self.text
    

class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

# abstract class for question
class Question(models.Model):
    text = models.CharField(max_length=100)
    
    def __str__(self):
        return self.text

class OneChoiceQuestion(Question):
    options = models.ManyToManyField(Option, related_name='options')
    
    def __str__(self):
        return self.text
    
class OpinionQuestion(Question):
    answers = models.CharField(max_length=100)

    def __str__(self):
        return self.text

class Quiz(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.IntegerField()
    title = models.CharField(max_length=100)
    description = models.TextField()
    quiestions = models.ManyToManyField(OneChoiceQuestion, related_name='questions')
    def __str__(self):
        return self.title

zavrsni/quiz/views.py
from asyncio import log
from datetime import datetime
import json
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.auth import logout as auth_logout
from quiz.models import Quiz
import pyrebase
import random
import firebase_admin
from firebase_admin import credentials, initialize_app, messaging
import os
from supabase import create_client
import qrcode 
import io
import base64

config = {
    "apiKey": "AIzaSyBcSUZ0zXsAEOY9t4PL82NqBKdGJFZgsX0",
    "authDomain": "zavrsni-proba-1.firebaseapp.com",
    "databaseURL": "https://zavrsni-proba-1-default-rtdb.europe-west1.firebasedatabase.app",
    "projectId": "zavrsni-proba-1",
    "storageBucket": "zavrsni-proba-1.appspot.com",
    "messagingSenderId": "649829209184",
    "appId": "1:649829209184:web:343823581c648622d65f05"
}

firebase = pyrebase.initialize_app(config)
auth = firebase.auth()
db = firebase.database()
if not firebase_admin._apps:
    cred = credentials.Certificate({
                "type": "service_account",
                "project_id": "zavrsni-proba-1",
                "private_key_id": "97a26ee5764a24f732c1c8c31f1753c6c01bf6bc",
                "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDWOthavG/nZGgg\nyU5hRlOjfbaaQe1ae3fadkTq4cFaEe0d09OcCi45CnD6V4RpLbXbg0z3ZPIZWONa\nhz1RN6Z8u/Y6xoLBARqEQE+/1WVcEiwJugxdE8CduCZPba5KEh2ZiRS3X865mSQL\n2bPyjxFRLH7+SD9vkBJE6504RWfFK5Ih1W4k2DlOysmYPR6om6IPFApX9RYFhci0\njc2JIkbIGPVhKoHY6TXNqoIJ6PY24TNU71AzTtoLTtRxN82G/xxygd6vi+8RAmYy\nYZm3ydBX2kljbHIup43qgKvbqxrk04Ih2+SjImajl8UMsTCpbFNDXCULgIns/lg/\nZcg9FUu3AgMBAAECggEAA9NchmTzu/ZvZEPUB36sWFtoBbcvAueji0jYuuJkg97q\nv2vx98kNbEKtznqo8wE4TH7lbUw7L+Kwz1liP0S2z2bCjegk8PIRGX2AhGoje5Ju\nK4+hUDmIaLNKKS70kX64p+4/wB/mNCryRC0+E73O+bEeuhxrgurYDgJbILnJ5vEe\nM9zj6GtLBZedMB9r035cg310lQewkdpRjx9KyLLxnJZGX1452b/OISEFIOdG4UEO\nDDCZx7g56tsOm8Og7WTspOtP7fZpcXsK3v12lOaZBOWrgdTmtGUYzODInlxEoi/G\nI4bhBJr/I7+JjjjqgKc1yQmwc+CRiMv5O5q/ZRP4qQKBgQD4CFyg7qvxFAtZit78\ne3wOMMtulTzF0ouRH3pql3khBZupALq/MKZBrukHwN3niW9w0Ltrz7vgClaxSdUe\nO1pX4xyjrQCwuEzyV8KuKnCbCNNDtronTxNEzHXMDaXs6vL+WCTsv/+KBeUeCxR5\nxCV+QqoQaAgcjN3bwox3Ku6buwKBgQDdHIOR8CHCT+ZGnzUqzHi/3iUCwSEa2nwP\nKiTVWPdQ4aX+N+lVJXTtD9lDneYjMildCjjbWbq4lRAGPwfUL1AIn3IrWKc5/sXa\np7oQlem9nzpD1UsAlRrXc0vzUGoqmHK1YFm9A0m1JxClBGzxd3VmoUsqPjBMaVlH\nklzaZ9FKNQKBgGEFxFYfhprTIG1yaS+SjkBuzeT/87neVkH6ckRn5DYKn41If8Ry\nH1bqOLWTuDnuBO24eNf/dpp48NiA7SDaTsi6SmWsMuzt6wuRUNIYP9wlY57FR6RA\nxmTPJfUgEZvPfCYKDMefgzJWg/1wkB3hoFj3ctbgGuwwHkjsnU2wOY4pAoGAT+Y3\n3QqLCG5a5fYt/jM5Bww9D4u+bLe60LgH61hktkNz+jM2C+CnKerqNbbfLKS5sbc5\n6Hm6MW0cB0XLjG80WolTdjpo41ofIO4vHEMv3aemJFD081buBiDRtzC9zHqeKNCS\nXOzNO7rMFvVMcM0cDWQHh1JFnbcL3gMTrpCJXmkCgYEA1eiEi0fKvjS+83Ku6YdV\nTcpyjGK8h8uRQshcXgApfc19kL6BSqo8f23a5FBVhRAfu1dBIIjBiLkJ/JmnhBI4\ngIgKgweHjEpwrYMO/Jo3Dx5unUbC4sLlDNQ/Eh5PYZmsNmHbPdJrrrLxNG7tjCeh\nVxzs964+1Wo26Lz0YfOCIyA=\n-----END PRIVATE KEY-----\n",
                "client_email": "firebase-adminsdk-4v8t0@zavrsni-proba-1.iam.gserviceaccount.com",
                "client_id": "111160597895199510004",
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-4v8t0%40zavrsni-proba-1.iam.gserviceaccount.com",
                "universe_domain": "googleapis.com"
        }
    )
    initialize_app(cred)

url = "https://kedeahnzxeepqtqkaiqi.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlZGVhaG56eGVlcHF0cWthaXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTYzODc5NjQsImV4cCI6MjAzMTk2Mzk2NH0.TmDiS62H4stznxshs62aqnfpvWY1k425pBksY34I6XA"
supabase = create_client(url, key)

def index(request):
    context = { }
    if 'token' in request.session:
        try:
            # supabase.auth.get_user(request.session['token'])
            context['user'] = request.session['token']
        except:
            request.session.flush()
        return render(request, 'quiz/index.html', context)
    else:
        return render(request, 'quiz/index.html')

def register(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        username = request.POST.get('username')
        try:
            user = supabase.auth.sign_up({ "email": email, "password": password })
            supabase.table('users').insert([{"name": username, 'email': email }]).execute()
            return redirect('quiz:index')
        except:
            messages.info(request, 'Invalid credentials')
            return redirect('quiz:register')    
    return render(request, 'registration/register.html')

def login(request):
    message = ""
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        try:
            supabase.auth.sign_in_with_password({ "email": email, "password": password })
            name = supabase.table('users').select("*").eq('email', email).execute()
            request.session['token'] = name.data[0]['name']
            return redirect('quiz:index') 
        except:
            message = "Incorrect email or password"
    return render(request, 'registration/login.html', {'message': message})

def logout(request):
    request.session.flush()
    return redirect('quiz:index')

def create_quiz(request):
    return render(request, 'quiz/create_quiz.html')

def create_one_choice(request):
    return render(request, 'quiz/create_one_choice.html')

def add_one_choice(request):
    if request.method == 'POST':
        one_choice_data(request)
    return redirect('quiz:user_quizzes')

def add_anonymous(request):
    if request.method == 'POST':
        anonymous_data(request)
    return redirect('quiz:user_quizzes')

def create_anonymous(request):
    return render(request, 'quiz/create_anonymous.html')

def one_choice_data(request):
    if 'token' not in request.session:
        return redirect('quiz:login')
    creator = request.session['token']
    quiz_name = request.POST.get('quizName')
    description = request.POST.get('quizDescription')
    # Add quiz to database
    creator_id = supabase.table('users').select('id').eq('name', creator).execute().data[0]['id']
    quiz_id = random.randint(100000, 999999)
    supabase.table('quizzes').insert([{"name": quiz_name, "user_id": creator_id, "description": description, "id": quiz_id, "type": "one_choice"}]).execute()
    quiz_id = supabase.table('quizzes').select('id').eq('name', quiz_name).execute().data[0]['id']
    question = request.POST.getlist('quizQuestion')
    answer1 = request.POST.getlist('quizAnswer1')
    answer2 = request.POST.getlist('quizAnswer2')  
    answer3 = request.POST.getlist('quizAnswer3')
    answer4 = request.POST.getlist('quizAnswer4')
    for i in range(len(question)):
        answer1Correct = request.POST.get('answer1Correct' + str(i)) == 'True'
        answer2Correct = request.POST.get('answer2Correct' + str(i)) == 'True'
        answer3Correct = request.POST.get('answer3Correct' + str(i)) == 'True'
        answer4Correct = request.POST.get('answer4Correct' + str(i)) == 'True' 
        image_url = request.POST.get('image_url' + str(i))
        answers = {
                "answer1": {
                    "text": answer1[i],
                    "correct": answer1Correct
                },
                "answer2": {
                    "text": answer2[i],
                    "correct": answer2Correct
                },
                "answer3": {
                    "text": answer3[i],
                    "correct": answer3Correct
                },
                "answer4": {
                    "text": answer4[i],
                    "correct": answer4Correct
                }
            }
        supabase.table('one_choice_question').insert({
            "quiz_id": quiz_id,
            "text": question[i],
            "answers": json.dumps(answers),
            "image_url": image_url
        }).execute()

def anonymous_data(request):
    if 'token' not in request.session:
        return redirect('quiz:login')
    creator = request.session['token']
    quiz_name = request.POST.get('quizName')
    description = request.POST.get('quizDescription')
    # Add quiz to database
    creator_id = supabase.table('users').select('id').eq('name', creator).execute().data[0]['id']
    quiz_id = random.randint(100000, 999999)
    supabase.table('quizzes').insert([{"name": quiz_name, "user_id": creator_id, "description": description, "id": quiz_id, "type": "anonymous"}]).execute()
    quiz_id = supabase.table('quizzes').select('id').eq('name', quiz_name).execute().data[0]['id']
    question = request.POST.getlist('quizQuestion')
    for i in range(len(question)):
        supabase.table('anonymous_question').insert({
            "quiz_id": quiz_id,
            "text": question[i],
            "answers": json.dumps({})
        }).execute()

def user_quizzes(request):
    creator_id = get_user_id(request.session['token'])
    user_quizzes = supabase.table('quizzes').select("*").eq('user_id', creator_id).execute().data
    return render(request, 'quiz/user_quizzes.html', {'quizzes': user_quizzes})

def quiz_details(request, quiz_id):
    quiz = get_quiz_data(quiz_id)
    return render(request, 'quiz/quiz_details.html', {'quiz': quiz, 'quiz_id': quiz_id})

def start_screen(request, quiz_id):
    quiz = get_quiz_data(quiz_id)
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(f"http://localhost:8000/{quiz_id}")

zavrsni/quiz/templates/quiz/ajax_players_list.html
<div id="players-list">
    <div class="quiz_start_screen">
        <h1>Code for enter {{ code_for_enter }}</h1>
        <h2>{{ quiz.name }}</h2>
        {% for player in players %}
            <div class="player_start_screen">
                {{ player.player_name }}<br>
            </div>
        {% endfor %}
        {{ players|length }} players
    </div>
</div>

zavrsni/quiz/templates/quiz/anonymous_question.html
{% extends "quiz/base_players.html" %}
{% block content %}
{{ question }}
    <form action="{% url 'quiz:anonymous_question' quiz_id %}" method="post">
        {% csrf_token %}
        <label for="answer">Enter your answer</label>
        <input type="text" id="answer" name="answer">
        <input type="hidden" id="device_token" name="device_token">
        <button type="submit">Submit</button>
    </form>
    <form action="{% url 'quiz:anonymous_question' quiz_id %}" method="post" style="display: none">
      {% csrf_token %}
      <input type="hidden" id="device_token" name="device_token">
      <input type="hidden" id="time_run_out" name="time_run_out" value="true">
      <input type="hidden" id="question" name="question">
      <input type="hidden" id="answers" name="answers">
      <input type="hidden" id="question_number" name="question_number">
      <button type="submit" id="time_run_out_submit">Submit</button>
  </form>
<script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-messaging.js"></script>

<script>
  var firebaseConfig = {
    apiKey: "AIzaSyBcSUZ0zXsAEOY9t4PL82NqBKdGJFZgsX0",
    authDomain: "zavrsni-proba-1.firebaseapp.com",
    databaseURL: "https://zavrsni-proba-1-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "zavrsni-proba-1",
    storageBucket: "zavrsni-proba-1.appspot.com",
    messagingSenderId: "649829209184",
    appId: "1:649829209184:web:343823581c648622d65f05"
  };
  firebase.initializeApp(firebaseConfig);

  const messaging = firebase.messaging();

  messaging.requestPermission()
    .then(function() {
      console.log('Notification permission granted.');
      return messaging.getToken();
    })
    .then(function(token) {
      console.log('FCM Token:', token);
      var deviceTokens = document.getElementsByName('device_token');
        for (var i = 0; i < deviceTokens.length; i++) {
            deviceTokens[i].value = token;
        }
    })
    .catch(function(err) {
      console.log('Unable to get permission to notify.', err);
    });

    messaging.onMessage((payload) => {
      document.getElementById('question').value = payload.data.question;
      document.getElementById('answers').value = payload.data.answers;
      document.getElementById('question_number').value = payload.data.question_number;
      document.getElementById('time_run_out_submit').click();
    });
</script>
{% endblock %}

zavrsni/quiz/templates/quiz/create_anonymous.html
{% extends "quiz/base.html" %}
{% block content %}
<h1 style="text-align: center;">Create new quiz</h1>
{% if request.session.token %}
   <form action="{% url 'quiz:add_anonymous' %}" method="post" class="create_quiz_form">
       {% csrf_token %}
       <label for="quizName">Name</label>
       <input type="text" name="quizName" id="quizName" placeholder="Enter name" required>
       <label for="quizDescription">Description</label>
       <input type="text" name="quizDescription" id="quizDescription" placeholder="Enter description" required><br>
       <div id="questions" class="questions_list"></div>
        <button type="button" id="anonymousQuestion">Add anonymous question</button>
       <button type="submit">Add new quiz</button> 
   </form>
   <script>
    let questionCount = 0;
    document.getElementById('anonymousQuestion').addEventListener('click', function() {
        event.preventDefault();

        const questionDiv = document.createElement('div');
        questionDiv.innerHTML = `
            {% load static%}
            <label for="quizQuestion${questionCount}">Question</label>
            <input type="text" name="quizQuestion" id="quizQuestion${questionCount}" placeholder="Enter question">
            <input type="hidden" name="questionCount" value="${questionCount}">
            <input type="hidden" name="answer1Correct${questionCount}" value="null">
            <input type="hidden" name="quizAnswer1" id="" placeholder="Enter answer">
            <input type="hidden" name="answer2Correct${questionCount}" value="null">
            <input type="hidden" name="quizAnswer2" id="" placeholder="Enter answer">
            <input type="hidden" name="answer3Correct${questionCount}" value="null">
            <input type="hidden" name="quizAnswer3" id="" placeholder="Enter answer">
            <input type="hidden" name="answer4Correct${questionCount}" value="null">
            <input type="hidden" name="quizAnswer4" id="" placeholder="Enter answer">
            <button class="remove_question" id="remove_question">
                <img src={% static 'quiz/delete_icon.png' %} alt="Remove question" width="20px" height="20px">
            </button><br>
        `;
        document.getElementById('questions').appendChild(questionDiv);
        questionCount++;

        questionDiv.querySelector('.remove_question').addEventListener('click', function() {
            questionDiv.remove();
        });
    })
    </script>
{% endif %}
{% endblock %}

zavrsni/quiz/templates/quiz/create_quiz.html
{% extends "quiz/base.html" %}
{% block content %}
<h1 style="text-align: center;">Create new quiz</h1>
{% if request.session.token %}
   {% comment %} <form action="{% url 'quiz:new_quiz' %}" method="post" class="create_quiz_form">
       {% csrf_token %}
       <label for="quizName">Name</label>
       <input type="text" name="quizName" id="quizName" placeholder="Enter name" required>
       <label for="quizDescription">Description</label>
       <input type="text" name="quizDescription" id="quizDescription" placeholder="Enter description" required><br>
       <div id="questions" class="questions_list"></div>
       <div class="hover_button">
        <button disabled>Add question</button>
            <div class="question_type">
                    <button id="addNewQuestion">Add one choice question</button> <button id="anonymousQuestion">Add anonymous question</button>
            </div>
       </div>
       <button type="submit">Add new quiz</button> 
   </form> {% endcomment %}
   <form action="{% url 'quiz:create_one_choice' %}" method="post" class="create_quiz_form">
    {% csrf_token %}
        <button type="submit">Create one choice quiz</button>
    </form>
    <form action="{% url 'quiz:create_anonymous' %}" method="post" class="create_quiz_form">
        {% csrf_token %}
       <button type="submit">Create anonymous quiz</button>
    </form>
   <script>
    let questionCount = 0;
    
    document.getElementById('addNewQuestion').addEventListener('click', function() {
        event.preventDefault();

        const questionDiv = document.createElement('div');
        questionDiv.innerHTML = `
            {% load static%}
            <label for="quizQuestions">Question</label>
            <input type="text" name="quizQuestion" id="quizQuestion" placeholder="Enter question" required>
            <input type="hidden" name="questionCount" value="${questionCount}">
            <label for="quizAnswers">Answers</label>
            <input type="checkbox" name="answer1Correct${questionCount}" value="True">
            <input type="text" name="quizAnswer1" id="" placeholder="Enter answer" required>
            <input type="checkbox" name="answer2Correct${questionCount}" value="True">
            <input type="text" name="quizAnswer2" id="" placeholder="Enter answer" required>
            <input type="checkbox" name="answer3Correct${questionCount}" value="True">
            <input type="text" name="quizAnswer3" id="" placeholder="Enter answer" required>
            <input type="checkbox" name="answer4Correct${questionCount}" value="True">
            <input type="text" name="quizAnswer4" id="" placeholder="Enter answer" required>
            <button class="remove_question" id="remove_question">
                <img src={% static 'quiz/delete_icon.png' %} alt="Remove question" width="20px" height="20px">
            </button><br>
        `;
        document.getElementById('questions').appendChild(questionDiv);
        questionCount++;

        questionDiv.querySelector('.remove_question').addEventListener('click', function() {
            questionDiv.remove();
        });
    });
    document.getElementById('anonymousQuestion').addEventListener('click', function() {
        event.preventDefault();

        const questionDiv = document.createElement('div');
        questionDiv.innerHTML = `
            {% load static%}
            <label for="quizQuestion${questionCount}">Question</label>
            <input type="text" name="quizQuestion" id="quizQuestion${questionCount}" placeholder="Enter question">
            <input type="hidden" name="questionCount" value="${questionCount}">
            <input type="hidden" name="answer1Correct${questionCount}" value="null">
            <input type="hidden" name="quizAnswer1" id="" placeholder="Enter answer">
            <input type="hidden" name="answer2Correct${questionCount}" value="null">
            <input type="hidden" name="quizAnswer2" id="" placeholder="Enter answer">
            <input type="hidden" name="answer3Correct${questionCount}" value="null">
            <input type="hidden" name="quizAnswer3" id="" placeholder="Enter answer">
            <input type="hidden" name="answer4Correct${questionCount}" value="null">
            <input type="hidden" name="quizAnswer4" id="" placeholder="Enter answer">
            <button class="remove_question" id="remove_question">
                <img src={% static 'quiz/delete_icon.png' %} alt="Remove question" width="20px" height="20px">
            </button><br>
        `;
        document.getElementById('questions').appendChild(questionDiv);
        questionCount++;

        questionDiv.querySelector('.remove_question').addEventListener('click', function() {
            questionDiv.remove();
        });
    })
    </script>
{% endif %}
{% endblock %}

zavrsni/quiz/templates/quiz/join_quiz.html
{% extends "quiz/base_players.html" %}
{% block content %}
<form action="{% url 'quiz:join_quiz' quiz_id %}" method="post" id="joinQuizForm">
    {% csrf_token %}
    <label for="player_name">Enter your name:</label>
    <input type="text" id="player_name" name="player_name" required>
    <input type="hidden" id="device_token" name="device_token">
    <button type="submit">Enter quiz</button>
</form>

<script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-messaging.js"></script>

<script>
  // Initialize Firebase
  var firebaseConfig = {
    apiKey: "AIzaSyBcSUZ0zXsAEOY9t4PL82NqBKdGJFZgsX0",
    authDomain: "zavrsni-proba-1.firebaseapp.com",
    databaseURL: "https://zavrsni-proba-1-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "zavrsni-proba-1",
    storageBucket: "zavrsni-proba-1.appspot.com",
    messagingSenderId: "649829209184",
    appId: "1:649829209184:web:343823581c648622d65f05"
  };
  firebase.initializeApp(firebaseConfig);

  const messaging = firebase.messaging();

  messaging.requestPermission()
    .then(function() {
      console.log('Notification permission granted.');
      return messaging.getToken();
    })
    .then(function(token) {
      console.log('FCM Token:', token);
      // You can now send this token to your server and store it
      // For example, you could send it as part of a form submission
      document.getElementById('device_token').value = token;
    })
    .catch(function(err) {
      console.log('Unable to get permission to notify.', err);
    });
</script>
{% endblock %}

zavrsni/quiz/templates/quiz/quiz_details.html
{% extends "quiz/base.html" %}
{% block content %}
<a href="{% url 'quiz:start_screen' quiz_id %}" class="start_quiz_button">Start quiz</a>
<div class="quiz_details">
<h1>{{ quiz.name }}</h1>
<p>{{ quiz.description }}</p>
    {% for question in quiz.questions %}
        <div class="quiz_details_question">
            {{ question.text }}
            {% if question.image_url %}
                <img src={{ question.image_url }} alt="{{ question.image_url }}" width="300px">
            {% endif %}
            <br>
            {% for answer_key, answer_value in question.answers.items %}
                Answer: {{ answer_value.text }}
                Correct: {{ answer_value.correct }}<br>
            {% endfor %}
            <br>
        </div>
    {% endfor %}
</div>
{% endblock %}

zavrsni/quiz/templates/quiz/quiz_results.html
{% extends "quiz/base.html" %}
{% block content %}
<h1>{{ quiz.quiz_name }}</h1>
{% for question in quiz.answers %}
    {{ question.text }}
    <br>
    {% for key, value in question.answers.items %}
        {{ value }}
        <br>
    {% endfor %}
{% endfor %}
{% for player in quiz.answers %}
    {% if player.player_name %}
        <p>{{ player.player_name }}: {{ player.points }} points</p>
    {% endif %}
{% endfor %}
<a href="{% url 'quiz:export_results' quiz.id %}" style="color: white; text-decoration: none; float: right">Export Results</a>

{% endblock %}